version: 2

project_name: devdoctor

before:
  hooks:
    - go test ./...

builds:
  - id: devdoctor
    main: ./cmd/devdoctor
    binary: devdoctor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/mahmudddddd/DevDoctor/internal/version.Version={{.Version}} -X github.com/mahmudddddd/DevDoctor/internal/version.Commit={{.Commit}} -X github.com/mahmudddddd/DevDoctor/internal/version.Date={{.Date}}

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
